source 'https://github.com/CocoaPods/Specs.git'
	pod 'DACircularProgress', :git => 'https://github.com/8ofproject/DACircularProgress'
	pod 'MWPhotoBrowser', :git => 'https://github.com/8ofproject/MWPhotoBrowser'
	pod 'Mantle', '= 2.0.2'
	pod 'AFNetworking', '= 2.5.4'
	pod 'TUSafariActivity', '= 1.0.4'