source 'https://github.com/CocoaPods/Specs.git'
	pod 'DACircularProgress', :git => 'https://github.com/8ofproject/DACircularProgress'
	pod 'MWPhotoBrowser', :git => 'https://github.com/8ofproject/MWPhotoBrowser'
	pod 'AFNetworking', '2.5.0'
	pod 'UINavigationItem+Loading', '~> 1.1'
	pod 'TUSafariActivity', '~> 1.0'
	pod 'CCBottomRefreshControl'