source 'https://github.com/CocoaPods/Specs.git'
	pod 'MWPhotoBrowser', '= 2.1.1'
	pod 'Mantle', '= 2.0.4'
	pod 'AFNetworking', '= 2.6.0'
	pod 'TUSafariActivity', '= 1.0.4'
	pod 'CCBottomRefreshControl', '= 0.5.1'
	pod 'YapDatabase', '= 2.7'