//
//  DVBconstants.h
//  dvach-browser
//
//  Created by Andy on 05/11/14.
//  Copyright (c) 2014 8of. All rights reserved.
//

#import <Foundation/Foundation.h>

// URL schemes
FOUNDATION_EXPORT NSString *const HTTPS_SCHEME;
FOUNDATION_EXPORT NSString *const HTTP_SCHEME;
FOUNDATION_EXPORT NSString *const GOOGLE_CHROME_HTTPS_SCHEME;
FOUNDATION_EXPORT NSString *const GOOGLE_CHROME_HTTP_SCHEME;

// URLS
FOUNDATION_EXPORT NSString *const STATUS_REQUEST_ADDRESS;
FOUNDATION_EXPORT NSString *const DVACH_BASE_URL;
FOUNDATION_EXPORT NSString *const DVACH_BASE_URL_WITHOUT_SCHEME;
FOUNDATION_EXPORT NSString *const COMPLAINT_URL;
FOUNDATION_EXPORT NSString *const GET_CAPTCHA_KEY_URL;
FOUNDATION_EXPORT NSString *const GET_CAPTCHA_IMAGE_URL;

// settings
FOUNDATION_EXPORT NSString *const USER_AGREEMENT_ACCEPTED;
FOUNDATION_EXPORT NSString *const OPEN_EXTERNAL_LINKS_IN_CHROME;
FOUNDATION_EXPORT NSString *const PASSCODE;
FOUNDATION_EXPORT NSString *const USERCODE;
FOUNDATION_EXPORT NSString *const BOARDS_LIST_VERSION;

//segues
FOUNDATION_EXPORT NSString *const SEGUE_TO_EULA;
FOUNDATION_EXPORT NSString *const SEGUE_TO_BOARD;
FOUNDATION_EXPORT NSString *const SEGUE_TO_THREAD;
FOUNDATION_EXPORT NSString *const SEGUE_TO_NEW_THREAD;
FOUNDATION_EXPORT NSString *const SEGUE_DISMISS_TO_THREAD;
FOUNDATION_EXPORT NSString *const SEGUE_DISMISS_TO_NEW_THREAD;

// cells
FOUNDATION_EXPORT NSString *const BOARD_CELL_IDENTIFIER;
FOUNDATION_EXPORT NSString *const DVB_BOARDVIEWCONTROLLER_IDENTIFIER;
FOUNDATION_EXPORT NSString *const THREAD_CELL_IDENTIFIER;